# Site settings
baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "River City Flooring"
theme = "hugo-agency-theme"


[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "River City Flooring"
	description = "Hardwood flooring installation, repairs, sanding and finishing for the greater Richmond area."

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "rivercityfloor@blachniet.com"


	# Navigation
	[params.navigation]
		brand = "River City Flooring"
		services = "Services"
		portfolio = "Portfolio"
		about = "About"
		team = "Comments"
		contact = "Contact"


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Hardwood Flooring Perfection"
		subtitle = "River City Flooring"
		buttonText = "Tell me more"
		imgAttribution = "[Red Oak Graphite [kitchen]](https://www.flickr.com/photos/74783045@N00/5622104990/in/photolist-9yNKWE-9yKFLx-cTpyno-cSyGXS-cTpxX3-azh6Q5-9K3RET-dqCrxA-dsTrTV-9K6Ffs-dsTs6Z-dsTs1k-dgBFaQ-4PfZTU-cTJoq7-5GK4uu-5GK3T9-5GK2eC-5GK1Po-9qL9gT-aCGHiL-g1aTeu-5GK1p7-7vyXHH-ibRSDg-9XiYM2-9xg6zF-9roUMX-7vv5K8-681jyf-9yNH4y-9yKFWa-cSyFfY-6ywvDa-7pR9m7-cTJnW5-cTJnys-8cr6Lv-domBJY-domC5U-domtrr-sod8KE-7pMf8B-cTJn4m-cTpy9w-cSyFGf-domBiq-cTpyt3-cSyGxQ-7VyrpK) by Boa-Franc"


	# Services section
	[params.services]
		title = "Services"
		subtitle = "We are here to meet all your hardwood flooring needs."

		[[params.services.list]]
			icon = "fa-shield"
			title = "Sanding & Finishing"
			description = "Whether they are newly installed or 20 years old, we can make your hardwood floors shine beautifully."

		[[params.services.list]]
			icon = "fa-magic"
			title = "Installation"
			description = "We install quality hardwood floors built to last."

		[[params.services.list]]
			icon = "fa-wrench"
			title = "Repairs"
			description = "We can repair just about any damage to your hardwood floors and make them look new again."


	# Portfolio section
	[params.portfolio]
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Portfolio"
		# subtitle = "Lorem ipsum dolor sit amet consectetur."

		[params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttonText = "Close project"


    # About section
	[params.about]
		title = "About"
		subtitle = "River City Flooring, Inc. was founded in **insert year here** by Kelly & Renee McDaniel. Kelly & Renee have been providing hardwood flooring installation, repair and maintenance to the greater Richmond area for **insert years here** years."
		# endpoint = "Be part<br>of our<br>story!"
		#
		# # The events will be listed from the top to the bottom.
		# # All images are stored under 'static/img/about'.
		# # Replace them with your own.
		# [[params.about.events]]
		# 	img = "1.jpg"
		# 	date = "2009-2011"
		# 	title = "Our Humble Beginnings"
		# 	description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
		#
		# [[params.about.events]]
		# 	img = "2.jpg"
		# 	date = "March 2011"
		# 	title = "An Agency is Born"
		# 	description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
		#
		# [[params.about.events]]
		# 	img = "3.jpg"
		# 	date = "December 2012"
		# 	title = "Our Humble Beginnings"
		# 	description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"
		#
		# [[params.about.events]]
		# 	img = "4.jpg"
		# 	date = "July 2014"
		# 	title = "Phase Two Expansion"
		# 	description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"


	# Team section
	[params.team]
		title = "What People Are Saying"
		subtitle = "Lorem ipsum dolor sit amet consectetur."
		description = ""

		[[params.team.comments]]
			comment = "They are great!"
			author = "Somebody"

		[[params.team.comments]]
			comment = "Beautiful, professional work. We love our new floors."
			author = "Somebody Else"

		[[params.team.comments]]
			comment = "River City Flooring made my 10 year old floors look brand new!"
			author = "Another Guy"

	# Client section
	# All the clients' logos are stored under 'static/img/logos'.
	# Replace them with your clients's logos.
	[[params.clients]]
		logo = "envato.jpg"
		link = "#"

	[[params.clients]]
		logo = "designmodo.jpg"
		link = "#"

	[[params.clients]]
		logo = "themeforest.jpg"
		link = "#"

	[[params.clients]]
		logo = "creative-market.jpg"
		link = "#"


	# Contact section
	[params.contact]
		title = "Contact us"
		subtitle  = "We would love to hear from you. Send us any questions or comments you may have!"
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
		copyright = "&copy; River City Flooring, Inc. 2015"

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "#"

		[[params.footer.social]]
			icon = "fa-facebook"
			link = "#"

		[[params.footer.social]]
			icon = "fa-linkedin"
			link = "#"

		[[params.footer.quicklinks]]
			text = "Privacy Policy"
			link = "#"

		[[params.footer.quicklinks]]
			text = "Terms of Use"
			link = "#"
